name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build ohif
      run: |
        mkdir Build
        cd Build
        ../Resources/CreateOHIFDist.sh
        cmake .. -DSTATIC_BUILD=ON -DCMAKE_BUILD_TYPE=Release
        make
    
