name: OHIF Compilation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build ohif
        run: |
          mkdir Build
          cd Build
          ../Resources/CreateOHIFDist.sh
          cmake .. -DSTATIC_BUILD=ON -DCMAKE_BUILD_TYPE=Release
          make
          ls
      - name: Build orthanc
        run: |
          cd Build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=~/Orthanc/Resources/MinGW-W64-Toolchain32.cmake \
            -DSTANDALONE_BUILD=ON \
            -DSTATIC_BUILD=ON \
            -DUSE_LEGACY_JSONCPP=ON
          make
          ls
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: libOrthancOHIF.so
      #     path: Build/libOrthancOHIF.so
