name: OHIF Compilation

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: sudo apt install -y tree g++-mingw-w64
      - name: build ohif(64)
        run: |
          mkdir Build && cd Build
          ../Resources/CreateOHIFDist.sh
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=../Resources/Orthanc/Toolchains/MinGW-W64-Toolchain64.cmake \
            -DSTANDALONE_BUILD=ON \
            -DSTATIC_BUILD=ON
          make
          ls
      - name: Build orthanc(64)
        run: |
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=~/Orthanc/Resources/MinGW-W64-Toolchain64.cmake \
            -DSTANDALONE_BUILD=ON \
            -DSTATIC_BUILD=ON \
          make
          ls

      - name: Upload artifact 64
        uses: actions/upload-artifact@v2
        with:
          name: libOrthancOHIF64.dll
          path: Build/libOrthancOHIF64.dll

      - name: Clear Build
        run: rm -rf Build

      - name: Build ohif(32)
        run: |
          mkdir Build && cd Build
          ../Resources/CreateOHIFDist.sh
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=../Resources/Orthanc/Toolchains/MinGW-W64-Toolchain32.cmake \
            -DSTANDALONE_BUILD=ON \
            -DSTATIC_BUILD=ON
          make
          ls

      - name: Build orthanc(32)
        run: |
          cd Build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=~/Orthanc/Resources/MinGW-W64-Toolchain32.cmake \
            -DSTANDALONE_BUILD=ON \
            -DSTATIC_BUILD=ON \

      - name: Upload artifact 32
        uses: actions/upload-artifact@v2
        with:
          name: libOrthancOHIF32.dll
          path: Build/libOrthancOHIF32.dll
